#!/usr/bin/env python2
# -*- coding: utf-8 -*-
from __future__ import print_function
import os
import sys
import argparse
from netrc import netrc
from hashlib import md5

import mechanize
from lxml import html

import logging

def get_grades(username, password):
    br = mechanize.Browser()

    # some saner defaults, not all of them needed right now
    br.addheaders = [('User-agent', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36')]
    br.set_handle_robots(False)
    br.set_handle_refresh(True)
    br.set_handle_redirect(True)

    # Really good debugging output actually (http headers)
    # br.set_debug_http(True)

    # Important, seems the way tucan does this is not compatible with mechanize
    br.set_handle_equiv(False)

    # open the tucan startsite (skip first redirect), input user/password
    br.open("https://www.tucan.tu-darmstadt.de/scripts/mgrqcgi?APPNAME=CampusNet&PRGNAME=EXTERNALPAGES&ARGUMENTS=-N000000000000001,-N000344,-Awelcome")
    br.select_form(nr=0)
    br.form["usrname"] = username
    br.form["pass"] = password
    resp = br.submit()

    # since we disabled the http equiv redirect we have to follow the link
    # manually
    br.follow_link(text_regex=u"^Startseite$")

    # navigate to exam results
    br.follow_link(text_regex=u"^Prüfungen$")
    br.follow_link(text_regex=u"^Semesterergebnisse$")
    br.follow_link(text_regex=u"^Prüfungsergebnisse$")

    tree = html.fromstring(br.response().read())
    tbody = tree.xpath(".//table[@class='nb list']/tbody")[0]

    grades = [[" ".join(unicode(td.text).strip().split())
               for td in tr.findall("td")][:-1]
              for tr in tbody.findall("tr")]
    return grades


def mail(recipient, subject, body):
    import subprocess

    proc = subprocess.Popen(["mail", "-s", subject, recipient],
                            stdin=subprocess.PIPE)
    proc.stdin.write(body)
    proc.stdin.close()


def notify(msg):
    from subprocess import Popen

    Popen(['notify-send', msg])


def parse_netrc():
    username, _, password = netrc().authenticators("www.tucan.tu-darmstadt.de")
    return username, password


def update_db(db, grades):
    if os.path.isfile(db):
        with open(db) as db_fp:
            old_digests = set(db_fp.read().split(os.linesep))
    else:
        old_digests = set()

    new_digests = {md5(repr(g)).hexdigest(): g for g in grades}

    if set(new_digests.keys()) != old_digests:
        with open(db, "w") as db_fp:
            db_fp.write(os.linesep.join(old_digests.union(new_digests.keys())))

        return [v for k, v in new_digests.items() if k not in old_digests]

    return None


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="TUCaN CLI",
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("--mail", "-m", type=str,
                        help="send email to this address on changes")
    parser.add_argument("--db", type=str,
                        default=os.path.expanduser("~/.local/tucandb"),
                        help="database file")
    parser.add_argument("--new", help="print only new grades", action="store_true")
    parser.add_argument("--notify", "-n", action="store_true",
                        help="send desktop notification on new grades")
    parser.add_argument("--json", "-j", help="output json", action="store_true")
    args = parser.parse_args()

    username, password = parse_netrc()
    grades = get_grades(username, password)

    if args.mail or args.new or args.notify:
        new_grades = update_db(args.db, grades)

        if new_grades:
            msg = os.linesep.join([g[0] + ": " + g[2] for g in new_grades])
            if args.mail:
                mail(args.mail, "New Grade in TUCaN", msg)
            if args.notify:
                notify(msg)
            if not args.mail and not args.notify:
                print(msg)
    else:
        if args.json:
            import json
            print(json.dumps(list(grades)))
        else:
            for grade in grades:
                print(grade[0] + ": " + grade[2])
